# Generated by Django 3.1.1 on 2020-11-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kfcImage', models.URLField()),
            ],
        ),
    ]
